version: '2'

services:
  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  nosqlclient:
    image: mongoclient/mongoclient
    ports:
      - "3001:3000"

volumes:
  mongo_data:

