version: '3'

services:
  web:
    build: .
    ports:
      - "3002:3000"
    environment:
      - MONGODB_URI=mongodb://mongo/main
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  nosqlclient:
    image: mongoclient/mongoclient
    ports:
      - "3001:3000"
    volumes:
      - nosqlclient_data:/data/db

volumes:
  mongo_data:
  nosqlclient_data:
